/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.52
 * Generated at: 2018-06-04 11:14:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.sns;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.Authentication;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Users/evert/OneDrive/Documents/workspace/stylecode-finalproject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/stylecode/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/Users/evert/OneDrive/Documents/workspace/stylecode-finalproject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/stylecode/WEB-INF/lib/spring-security-taglibs-3.2.3.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1395715282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1527468789553L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-3.2.3.RELEASE.jar", Long.valueOf(1528090598533L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.springframework.security.core.context.SecurityContextHolder");
    _jspx_imports_classes.add("org.springframework.security.core.Authentication");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>Social Media</title>\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 내부 자바스크립트 -->\r\n");
      out.write("\t<script src=\"/resources/sns/js/jquery-3.3.1.js\"></script>\r\n");
      out.write("\t<script src=\"/resources/sns/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"/resources/sns/bootstrap-switch/js/bootstrap-switch.min.js\"></script>\r\n");
      out.write("\t<script src=\"/resources/sns/js/socialyte.min.js\"></script>\r\n");
      out.write("\t<script src=\"/resources/sns/js/list.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 외부 자바스크립트 -->\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("\t<script src=\"https://twemoji.maxcdn.com/twemoji.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 외부 CSS -->\r\n");
      out.write("\t<link href=\"https://fonts.googleapis.com/css?family=Poppins:300,400,600,700\" rel=\"stylesheet\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.0.13/css/all.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 내부 CSS -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/resources/sns/bootstrap/css/bootstrap.min.css\" type=\"text/css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/resources/sns/bootstrap-switch/css/bootstrap-switch.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/resources/sns/css/sns.css\" type=\"text/css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/resources/dist/css/AdminLTE.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"sns\">\r\n");
      out.write("\t<!-- 헤더 및 네비 -->\r\n");
      out.write("\t<header class=\"text-right\">\r\n");
      out.write("\t\t<form class=\"text-left search\" method=\"GET\">\r\n");
      out.write("\t\t\t<input name=\"q\" type=\"text\" placeholder=\"Search..\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<div class=\"menu-icon\">\r\n");
      out.write("\t\t\t<div class=\"dropdown\">\r\n");
      out.write("\t\t\t\t<span class=\"dropdown-toggle\" role=\"button\" id=\"dropdownSettings\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"true\"> <span class=\"hidden-xs hidden-sm\">Settings</span> <i class=\"fa fa-cogs\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-right\" aria-labelledby=\"dropdownSettings\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"settings.html\" title=\"Settings\" data-toggle=\"modal\" data-target=\"#settingsmodal\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fa fa-wrench\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-8 text-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>Settings</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" title=\"Settings\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fa fa-question\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-8 text-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>FAQ</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" title=\"Settings\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fa fa-sign-out\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-8 text-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>Logout</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"second-icon dropdown menu-icon\">\r\n");
      out.write("\t\t\t<span class=\"dropdown-toggle\" role=\"button\" id=\"dropdownNotification\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"true\"> <span class=\"hidden-xs hidden-sm\">Notifications</span> <i class=\"far fa-bell\" aria-hidden=\"true\"></i> <span class=\"badge\">2</span>\r\n");
      out.write("\t\t\t</span>\r\n");
      out.write("\t\t\t<ul class=\"dropdown-menu dropdown-menu-right\" aria-labelledby=\"dropdownNotification\">\r\n");
      out.write("\t\t\t\t<li class=\"new-not\"><a href=\"#\" title=\"User name comment\"><img src=\"/resources/sns/img/sample/user2.jpg\" alt=\"User name\" class=\"img-circle img-user-mini\"> User comments your post</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"new-not\"><a href=\"#\" title=\"User name comment\"><img src=\"/resources/sns/img/sample/user3.jpg\" alt=\"User name\" class=\"img-circle img-user-mini\"> User comments your post</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" title=\"User name comment\"><img src=\"/resources/sns/img/sample/user4.jpg\" alt=\"User name\" class=\"img-circle img-user-mini\"> User comments your post</a></li>\r\n");
      out.write("\t\t\t\t<li role=\"separator\" class=\"divider\"></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" title=\"All notifications\">All Notifications</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"second-icon menu-icon\">\r\n");
      out.write("\t\t\t<span><a href=\"personal-profile.html\" title=\"Profile\"><span class=\"hidden-xs hidden-sm\">Profile</span> <i class=\"fa fa-user\" aria-hidden=\"true\"></i></a> </span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"second-icon menu-icon\">\r\n");
      out.write("\t\t\t<span><a href=\"wall.html\" title=\"Wall\"><span class=\"hidden-xs hidden-sm\">Wall</span> <i class=\"fa fa-database\" aria-hidden=\"true\"></i></a> </span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<!-- 왼쪽 사이드 바 회원 프로필 -->\r\n");
      out.write("\t<div class=\"sidebar-nav\">\r\n");
      out.write("\t\t<a href=\"personal-profile.html\" title=\"Profile\"> <img src=\"/resources/sns/img/sample/user.jpg\" alt=\"User name\" class=\"img-circle img-user\">\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t<h2 class=\"text-center hidden-xs\">\r\n");
      out.write("\t\t\t<a href=\"personal-profile.html\" title=\"Profile\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\r\n");
      out.write("\t\t</h2>\r\n");
      out.write("\t\t<p class=\"text-center user-description hidden-xs\">\r\n");
      out.write("\t\t\t<i>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</i>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 포스트 작성 및 목록 -->\r\n");
      out.write("\t<div class=\"content-posts active\" id=\"posts\">\r\n");
      out.write("\t\t<div class=\"primary-content\">\r\n");
      out.write("\t\t\t<div id=\"posts-container\" class=\"container-fluid container-posts\">\r\n");
      out.write("\t\t\t\t<!-- 포스트 작성 -->\r\n");
      out.write("\t\t\t\t<form id=\"registerForm\" role=\"form\" method=\"post\" action=\"/sns/register\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card-post\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-3 col-sm-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"personal-profile.html\" title=\"Profile\"> <img src=\"/resources/sns/img/sample/user.jpg\" alt=\"User name\" class=\"img-circle img-user\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-9 col-sm-10 info-user\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- 작성자 이름 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"mid\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"personal-profile.html\" title=\"Profile\">My User</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i>now</i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 게시물 내용 -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-8 col-sm-offset-2 data-post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<textarea class=\"form-control\" name=\"bdcontent\" placeholder=\"회원님 무슨 생각을 하시나요?\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 파일 업로드 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"fileDrop\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"exampleInputEmali1\">File DROP Here</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"mailbox-attachments clearfix uploadedList\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 작성 버튼 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"submit-post\">Post</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--Close #posts-container-->\r\n");
      out.write("\t\t<div class=\"sidebar-right hidden-xs hidden-sm\">\r\n");
      out.write("\t\t\t<div class=\"card-post\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<i>Suggested post</i>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" title=\"Company\">Company</a>\r\n");
      out.write("\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/resources/sns/img/sample/company.jpg\" alt=\"Suggested post\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"card-post\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t<h3>Popular Users</h3>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-3 popular-img\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"> <img src=\"/resources/sns/img/sample/user.jpg\" alt=\"User name\" class=\"img-circle\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-3 popular-img\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"> <img src=\"/resources/sns/img/sample/user2.jpg\" alt=\"User name\" class=\"img-circle\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-3 popular-img\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"> <img src=\"/resources/sns/img/sample/user3.jpg\" alt=\"User name\" class=\"img-circle\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-3 popular-img\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"> <img src=\"/resources/sns/img/sample/user4.jpg\" alt=\"User name\" class=\"img-circle\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-3 popular-img\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"> <img src=\"/resources/sns/img/sample/user5.jpg\" alt=\"User name\" class=\"img-circle\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-3 popular-img\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"> <img src=\"/resources/sns/img/sample/user6.jpg\" alt=\"User name\" class=\"img-circle\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-3 popular-img\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"> <img src=\"/resources/sns/img/sample/user7.jpg\" alt=\"User name\" class=\"img-circle\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-3 popular-img\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"> <img src=\"/resources/sns/img/sample/user8.jpg\" alt=\"User name\" class=\"img-circle\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"card-post\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t<h3>Popular Photos</h3>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-4 popular-img\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"> <img src=\"/resources/sns/img/sample/photo1.jpg\" alt=\"User name\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-4 popular-img\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"> <img src=\"/resources/sns/img/sample/photo2.jpg\" alt=\"User name\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-4 popular-img\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"> <img src=\"/resources/sns/img/sample/photo3.jpg\" alt=\"User name\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-4 popular-img\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"> <img src=\"/resources/sns/img/sample/photo4.jpg\" alt=\"User name\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-4 popular-img\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"> <img src=\"/resources/sns/img/sample/photo5.jpg\" alt=\"User name\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-4 popular-img\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"> <img src=\"/resources/sns/img/sample/photo6.jpg\" alt=\"User name\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-4 popular-img\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"> <img src=\"/resources/sns/img/sample/photo7.jpg\" alt=\"User name\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-4 popular-img\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"> <img src=\"/resources/sns/img/sample/photo8.jpg\" alt=\"User name\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-4 popular-img\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"> <img src=\"/resources/sns/img/sample/photo9.jpg\" alt=\"User name\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"loading\">\r\n");
      out.write("\t\t<img src=\"/resources/sns/img/sample/load.gif\" alt=\"loader\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Close #posts -->\r\n");
      out.write("\t<!-- Modal container for settings--->\r\n");
      out.write("\t<div id=\"settingsmodal\" class=\"modal fade text-center\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script id=\"template\" type=\"text/x-handlebars-template\">\r\n");
      out.write("<li>\r\n");
      out.write("\t<span class=\"mailbox-attachment-icon has-img\"><img src=\"{{imgsrc}}\" alt=\"Attachment\"></span>\r\n");
      out.write("\t<div class=\"mailbox-attachment-info\">\r\n");
      out.write("\t\t<a href=\"{{getLink}}\" class=\"mailbox-attachment-name\">{{fileName}}</a>\r\n");
      out.write("\t\t<a href=\"{{fullName}}\" class=\"btn btn-default btn-xs pull-right delbtn\"><i class=\"fas fa-times\"></i></a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</li>\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"/resources/sns/js/upload.js\"></script>\r\n");
      out.write("<script src=\"/resources/sns/js/scroll-pagination.js\"></script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
