/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.52
 * Generated at: 2018-05-30 06:53:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class spmList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1525949837369L));
    _jspx_dependants.put("jar:file:/C:/finalproject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/stylecode/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/bootstrap/js/bootstrap.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../resources/bootstrap/css/bootstrap.css\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<h3>관리자 페이지</h3>\r\n");
      out.write("\t<div>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t<form action=\"admin/accept\">\r\n");
      out.write("\t\t<!--  버튼 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"container\" style=\"margin: 10px;\">\r\n");
      out.write("\t\t\t\t\t  <div class=\"row\">\r\n");
      out.write("\t\t\t\t\t    <div class=\"col-sm\">\r\n");
      out.write("\t\t\t\t\t      <input style=\"margin-top: 15px;\" type=\"checkbox\" name=\"checkAll\" id=\"th_checkAll\" />&emsp;전체 선택\r\n");
      out.write("\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t  <div class=\"col-sm\">\r\n");
      out.write("\t\t\t\t\t      \r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t <div class=\"col-sm\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-outline-dark\" id=\"accept\">승인</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-outline-dark\" id=\"refuse\">거절</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!--           쇼핑몰 리스트                      -->\r\n");
      out.write("\t\t<div id=\"spmList\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 체크박스 전체체크/해제 하는 js -->\r\n");
      out.write("\t\t$(\"#th_checkAll\").on(\"click\", function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t    if( $(\"#th_checkAll\").is(':checked') ){\r\n");
      out.write("\t\t\t      $(\"input[name=checkRow]\").prop(\"checked\", true);\r\n");
      out.write("\t\t\t    }else{\r\n");
      out.write("\t\t\t      $(\"input[name=checkRow]\").prop(\"checked\", false);\r\n");
      out.write("\t\t\t    };\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- 템플릿 -->\r\n");
      out.write("<script id=\"template\" type=\"text/x-handlebars-template\">\r\n");
      out.write("\t{{#each .}}\r\n");
      out.write("\t<p class=\"list-group-item list-group-item-action list-group-item-light\" style=\"background-color: #FFFFFF;\">\r\n");
      out.write("\t\t\t<input type=\"checkbox\" id=\"checkRow\" name=\"checkRow\" value=\"{{spmEnrollNo}}\">\r\n");
      out.write("\t\t\t<img width=\"100px\" height=\"100px\" alt=\"사진이 없음\" class=\"img-circle\" src=\"{{shoppingmallVO.smpTn}}\"> \r\n");
      out.write("\t\t\t<span>&emsp;</span>\r\n");
      out.write("\t\t\t<a class=\"btn spmNm\" href={{spmURL}}><b style=\"color: black;\">{{shoppingMallVO.spmNm}}</b></a>\t\t\r\n");
      out.write("\t\t\t<span class=\"spmInfo\">&emsp;{{shoppingMallVO.spmClassifcn}}</span>\r\n");
      out.write("\t\t\t<span class=\"spmInfo\">&emsp;{{shoppingMallVO.spmInfo}}</span>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<span class=\"spmInfo\">&emsp;{{mId}}</span>\r\n");
      out.write("\t</p>\r\n");
      out.write("\t{{/each}}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("/*           쇼핑몰 리스트                  */\r\n");
      out.write("var template = Handlebars.compile($(\"#template\").html());\r\n");
      out.write("\r\n");
      out.write("function spmList() {\r\n");
      out.write("\t$.getJSON(\"/admin/all\",function(data){\r\n");
      out.write("\t\tconsole.log(data.length);\r\n");
      out.write("\t\t$(\"#spmList\").html(template(data));\r\n");
      out.write("\t});\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("spmList();\r\n");
      out.write("\r\n");
      out.write("//체크박스 속에 val를 받을 배열 선언\r\n");
      out.write("//var array = new Array();\r\n");
      out.write("\tvar array = [];\r\n");
      out.write("/*                 승인                                   */\r\n");
      out.write(" $(\"#accept\").on(\"click\", function(){\r\n");
      out.write("\t   \r\n");
      out.write("\t $('#checkRow:checked').each(function() { \t      \r\n");
      out.write("\t\t   array.push($(this).val());\t       \r\n");
      out.write("\t   });\r\n");
      out.write("\t   if(array.length == 0){\r\n");
      out.write("\t\t  alert(\"체크해주세요\");\r\n");
      out.write("\t   }else{\r\n");
      out.write("\t\t   $.ajax({\r\n");
      out.write("\t\t\t   url :'/admin/accept',\r\n");
      out.write("\t\t\t   type : 'post',\r\n");
      out.write("\t\t\t   dataType: 'json',\r\n");
      out.write("\t\t\t   data:{array : array},\r\n");
      out.write("\t\t\t   success : function() {\r\n");
      out.write("\t\t\t\t\talert(\"승인 되었습니다.\");\r\n");
      out.write("\t\t\t\t\tspmList();\t\r\n");
      out.write("\t\t\t\t\tif(result == \"SUCCESS\"){\r\n");
      out.write("\t\t\t\t\t\talert(\"SUCCESS\");\r\n");
      out.write("\t\t\t\t\t};\t\r\n");
      out.write("\t\t\t\t\t}\t   \r\n");
      out.write("\t\t   });\r\n");
      out.write("\t\t\talert(\"승인 되었습니다.\");\r\n");
      out.write("\t\t\tspmList();\t\r\n");
      out.write("\t   }\r\n");
      out.write("\r\n");
      out.write("\t   \r\n");
      out.write("\t   \r\n");
      out.write("\t   \r\n");
      out.write("\t   \r\n");
      out.write("\t   \r\n");
      out.write("\t   \r\n");
      out.write(" });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* $(\"#accept\").on(\"click\", function(){\r\n");
      out.write("\t\t//체크박스에 체크된 val를 받아온다.\r\n");
      out.write("\t   $('#checkRow:checked').each(function() { \t      \r\n");
      out.write("\t\t   array.push($(this).val());\t       \r\n");
      out.write("\t   });\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(array.length == 0){\r\n");
      out.write("\t\t\talert(\"선택해 주세요.\");\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t)}; */\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("/* \t\t\t   $.ajax({\r\n");
      out.write("\t\t\t\t   type : 'post',\r\n");
      out.write("\t\t\t\t   url : '/admin/accept',\r\n");
      out.write("\t\t\t\t   data :{array : array} ,\r\n");
      out.write("\t\t\t\t   dataType:'json',\r\n");
      out.write("\t\t\t\t   traditional : true,\r\n");
      out.write("\t\t\t\t   success : function(result) {\r\n");
      out.write("\t\t\t\t\t\tif(result == \"SUCCESS\"){\r\n");
      out.write("\t\t\t\t\t\t\talert(\"승인 되었습니다.\");\r\n");
      out.write("\t\t\t\t\t\t\tspmList();\t\r\n");
      out.write("\t\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t\t\tarray = new Array();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t   }\r\n");
      out.write("\t\t\t   }); */\r\n");
      out.write("\r\n");
      out.write("\t\t\t   \r\n");
      out.write("\r\n");
      out.write("/*                  거절                                */\r\n");
      out.write(" \r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- <script>\r\n");
      out.write(" var source = $(\"#template\").html();\r\n");
      out.write(" var template = Handlebars.compile(source);\r\n");
      out.write(" var data = 데이터;\r\n");
      out.write(" function getAllList() {\r\n");
      out.write("\t\r\n");
      out.write("\t $.getJSON(\"/admin/all\", function(data){\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t \r\n");
      out.write("\t\t /* data내용을 넣은 template를  replies div 안에 넣는다. */\r\n");
      out.write("\t\t $(\"#replies\").html(template(data));\r\n");
      out.write("\t });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(" </script> -->\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/admin/spmList.jsp(47,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("SPM");
      // /WEB-INF/views/admin/spmList.jsp(47,3) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/admin/spmList.jsp(47,3) '${list}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t<p class=\"list-group-item list-group-item-action list-group-item-light\" style=\"background-color: #FFFFFF;\">\r\n");
            out.write("\t\t\t\t\t<input type=\"checkbox\"  name=\"checkRow\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${spmEnrollNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"> \r\n");
            out.write("\t\t\t\t\t<img width=\"100px\" height=\"100px\" alt=\"사진이 없음\" class=\"img-circle\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${style.tm }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"> \r\n");
            out.write("\t\t\t\t\t<span>&emsp;</span><b style=\"color: black;\">스타일난다</b> \t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t<span class=\"spmInfo\">&emsp;관리자 이름</span>\r\n");
            out.write("\t\t\t\t\t<span class=\"spmInfo\">&emsp;스타일난다 입니다.</span>\r\n");
            out.write("\t\t\t\t</p>\r\n");
            out.write("\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
