/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.52
 * Generated at: 2018-05-29 08:39:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.bookmark;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import stylecode.kosta180.domain.ShoppingMallVO;
import java.util.List;

public final class bookmarklist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/bookmark/../header.jsp", Long.valueOf(1527583186264L));
    _jspx_dependants.put("/WEB-INF/views/bookmark/../footer.jsp", Long.valueOf(1527580614290L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1525949837369L));
    _jspx_dependants.put("jar:file:/C:/finalproject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/stylecode/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("stylecode.kosta180.domain.ShoppingMallVO");
    _jspx_imports_classes.add("java.util.List");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/bootstrap/js/bootstrap.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../resources/bootstrap/css/bootstrap.css\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>쇼핑몰 즐겨찾기</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".list-group a {\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\tfont-family: NanumGothic;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu_tit {\r\n");
      out.write("\tfont-size: 35px;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\tfont-family: NanumGothic;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ic_new {\r\n");
      out.write("\tfont-size: 35px;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\tfont-family: NanumGothic;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h2 {\r\n");
      out.write("\tmargin: 30px 0;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");

	List<ShoppingMallVO> list =(List)request.getAttribute("list");

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<!-- 부트스트랩  프레임워크 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/bootstrap/css/bootstrap.min.css\" />\r\n");
      out.write("<!-- CUSTOM  CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/bootstrap/css/header.css\" />\r\n");
      out.write("<!-- FonTello  CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/bootstrap/css/fontello.css\" />\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<title>header</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div id=\"hTitle\"><a href=\"../index.jsp\" style=\"color:black;\">Middle Project</a></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div id=\"hLMn\" class=\"col-11\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a href=\"../index.jsp\">상품추천</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a href=\"../LoginProduct/productlist.jsp\">상품검색</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a href=\"../shoppingmall/index.html\">쇼핑몰</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a href=\"../printBoard.do\">모아보기</a></li>\r\n");
      out.write("\t\t\t</ul>\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"hRMn\" class=\"col-1\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<!-- fontello 아이콘 사용을 위한 부분  -->\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a href=\"../bookmark/bookmarklist.do\">&#xe800</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a href=\"../LoginProduct/login.jsp\">&#xe802</a></li>\t\t\t\t\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\" hidden >&#xe803</li>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a href=\"#\">&#xe801</a></li>\r\n");
      out.write("\t\t\t</ul>\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- JQuery JavaScript 추가  -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"../resources/bootstrap/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<!-- Popper JavaScript 추가 -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"../resources/bootstrap/js/popper.js\"></script>\r\n");
      out.write("<!-- Bootstrap JavaScript 추가 -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"../resources/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/bootstrap/js/bootstrap.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<h2 style=\"margin-left: 200px;\">\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"menu_tit\">나만의<em class=\"ic_new\">\r\n");
      out.write("\t\t\t\t\tBookMark</em></a>\r\n");
      out.write("\t\t</h2>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 즐겨찾기 리스트 -->\r\n");
      out.write("\t\t<div class=\"list-group\"\r\n");
      out.write("\t\t\tstyle=\"margin-left: 200px; margin-right: 200px;\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<!-- 부트스트랩  프레임워크 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/bootstrap/css/bootstrap.min.css\" />\r\n");
      out.write("<!-- CUSTOM  CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/bootstrap/css/rcCustom.css\" />\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<title>footer</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<footer class=\"page-footer font-small unique-color-dark pt-0\">\r\n");
      out.write("<hr class=\"deep-purple accent-6 mb-0 mt-0 d-inline-block mx-auto\" \r\n");
      out.write("\tstyle=\"width: 1600px;\">\r\n");
      out.write("<br>\r\n");
      out.write("<!--Footer Links-->\r\n");
      out.write("<div class=\"container mt-5 mb-0 text-center text-md-left\">\r\n");
      out.write("\t<div class=\"row mt-3\">\r\n");
      out.write("<!--고객센터 문의-->\r\n");
      out.write("<div class=\"col-md-1 col-lg-4 col-xl-3 mb-4 mx-auto mb-4 \">\r\n");
      out.write("\t<h6 class=\"text-uppercase font-weight-bold\">\r\n");
      out.write("\t\t<strong>고객센터 문의</strong>\r\n");
      out.write("\t</h6>\r\n");
      out.write("\t<hr class=\"deep-purple accent-2 mb-2 mt-0 d-inline-block mx-auto\"\r\n");
      out.write("\t\tstyle=\"width: 130px;\">\r\n");
      out.write("\t<p id=\"footercontents\">\r\n");
      out.write("\t\t<strong>전화문의</strong> 0000-0000<br> <strong>월-금</strong>\r\n");
      out.write("\t\t9:00-18:00<br> <strong>이메일</strong> aa@aa.com<br>\r\n");
      out.write("\t</p>\r\n");
      out.write("</div>\r\n");
      out.write("<!--/.고객센터 문의n-->\r\n");
      out.write("\r\n");
      out.write("<!--입점신청-->\r\n");
      out.write("<div class=\"col-md-2 col-lg-2 col-xl-3 mx-auto mb-4\">\r\n");
      out.write("\t<h6 class=\"text-uppercase font-weight-bold\">\r\n");
      out.write("\t\t<strong>입점신청</strong>\r\n");
      out.write("\t</h6>\r\n");
      out.write("\t<hr class=\"deep-purple accent-2 mb-2 mt-0 d-inline-block mx-auto\"\r\n");
      out.write("\t\tstyle=\"width: 100px;\">\r\n");
      out.write("\t<p id=\"footercontents\">\r\n");
      out.write("\t\t<strong>전화문의</strong> 0000-0000<br> <strong>월-금</strong>\r\n");
      out.write("\t\t9:00-18:00<br> <strong>이메일</strong> aa@aa.com<br>\r\n");
      out.write("\t</p>\r\n");
      out.write("</div>\r\n");
      out.write("<!--/.입점신청-->\r\n");
      out.write("\r\n");
      out.write("<!--광고문의-->\r\n");
      out.write("<div class=\"col-md-3 col-lg-2 col-xl-3 mx-auto mb-4\">\r\n");
      out.write("\t<h6 class=\"text-uppercase font-weight-bold\">\r\n");
      out.write("\t\t<strong>광고문의</strong>\r\n");
      out.write("\t</h6>\r\n");
      out.write("\t<hr class=\"deep-purple accent-2 mb-2 mt-0 d-inline-block mx-auto\"\r\n");
      out.write("\t\tstyle=\"width: 100px;\">\r\n");
      out.write("\t<p id=\"footercontents\">\r\n");
      out.write("\t\t<strong>전화문의</strong> 0000-0000<br> <strong>월-금</strong>\r\n");
      out.write("\t\t9:00-18:00<br> <strong>이메일</strong> aa@aa.com<br>\r\n");
      out.write("\t</p>\r\n");
      out.write("</div>\r\n");
      out.write("<!--/.광고문의-->\r\n");
      out.write("\r\n");
      out.write("<!--공지사항-->\r\n");
      out.write("<div class=\"col-md-4 col-lg-3 col-xl-3  mx-auto mb-4\">\r\n");
      out.write("\t<h6 class=\"text-uppercase font-weight-bold\">\r\n");
      out.write("\t\t<strong>공지사항</strong>\r\n");
      out.write("\t</h6>\r\n");
      out.write("\t<hr class=\"deep-purple accent-2 mb-2 mt-0 d-inline-block mx-auto\"\r\n");
      out.write("\t\tstyle=\"width: 100px;\">\r\n");
      out.write("\t<p id=\"footercontents\">\r\n");
      out.write("\t\t<strong>전화문의</strong> 0000-0000<br> <strong>월-금</strong>\r\n");
      out.write("\t\t9:00-18:00<br> <strong>이메일</strong> aa@aa.com<br>\r\n");
      out.write("\t</p>\r\n");
      out.write("</div>\r\n");
      out.write("<!--/.공지사항-->\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!--/.Footer Links-->\r\n");
      out.write("\r\n");
      out.write("<!-- Copyright-->\r\n");
      out.write("<div class=\"footer-copyright py-3 text-center\" id=\"footerbottom\">\r\n");
      out.write("\t<hr class=\"deep-purple accent-6 mb-4 mt-0 d-inline-block mx-auto\"\r\n");
      out.write("\t\tstyle=\"width: 1600px;\">\r\n");
      out.write("\t<br> 이름(주) | 서울특별시 금천구 가산동 371-47 이노플렉스 1차 2층 | 대표: 롸롸 |\r\n");
      out.write("\t사업자등록번호: 000-00-00000 | 통신판매업 신고번호: 제 2018-서울금천-00000 호<br>\r\n");
      out.write("\t대표전화: 0000-0000 | Email: aa@aa.com | 개인정보보호책임자: 롸롸, 롸롸<br> ©2018\r\n");
      out.write("\tMiddle Inc. All Rights Reserved<br>\r\n");
      out.write("</div>\r\n");
      out.write("<!--/.Copyright -->\r\n");
      out.write("</footer>\r\n");
      out.write("\t\r\n");
      out.write("<!-- JQuery JavaScript 추가  -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"../resources/bootstrap/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<!-- Popper JavaScript 추가 -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"../resources/bootstrap/js/popper.js\"></script>\r\n");
      out.write("<!-- Bootstrap JavaScript 추가 -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"../resources/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/bookmark/bookmarklist.jsp(57,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("i");
      // /WEB-INF/views/bookmark/bookmarklist.jsp(57,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/bookmark/bookmarklist.jsp(57,4) '${list}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t<p\r\n");
            out.write("\t\t\t\t\t\tclass=\"list-group-item list-group-item-action list-group-item-white\">\r\n");
            out.write("\t\t\t\t\t\t<img width=\"100px\" height=\"100px\" alt=\"사진이 없음\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.spmTn}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("\t\t\t\t\t\t<a id=\"spmbm\" href=\"../spmDetail/Spmdetail.do?spmEnrollNo=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.spmEnrollNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("\t\t\t\t\t\t\t<span>&emsp;</span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.spmNm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a><span>&emsp;/스타일태그/</span><span>&emsp;&emsp;&emsp;</span>\r\n");
            out.write("\t\t\t\t\t\t<a href=\"/bookmark/deletebookmark?spmEnrollNo=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.spmEnrollNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("\t\t\t\t\t\t\t<button\r\n");
            out.write("\t\t\t\t\t\t\t\tstyle=\"position: absolute; right: 2%; border: none; background: none;\">\r\n");
            out.write("\t\t\t\t\t\t\t\t<img  src=\"../resources/MH/images/delete.png\">\r\n");
            out.write("\t\t\t\t\t\t\t</button>\r\n");
            out.write("\t\t\t\t\t\t</a>\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t\t</p>\r\n");
            out.write("\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
