/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2018-06-07 02:34:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<!-- 부트스트랩  프레임워크 -->\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/YJH/bootstrap/css/bootstrap.min.css\" />\n");
      out.write("<!-- CUSTOM  CSS -->\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/YJH/bootstrap/css/rcCustom.css\" />\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("<title>footer</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<footer class=\"page-footer font-small unique-color-dark pt-0\">\n");
      out.write("<hr class=\"deep-purple accent-6 mb-0 mt-0 d-inline-block mx-auto\" \n");
      out.write("\tstyle=\"width: 1600px;\">\n");
      out.write("<br>\n");
      out.write("<!--Footer Links-->\n");
      out.write("<div class=\"container mt-5 mb-0 text-center text-md-left\">\n");
      out.write("\t<div class=\"row mt-3\">\n");
      out.write("<!--고객센터 문의-->\n");
      out.write("<div class=\"col-md-1 col-lg-4 col-xl-3 mb-4 mx-auto mb-4 \">\n");
      out.write("\t<h6 class=\"text-uppercase font-weight-bold\">\n");
      out.write("\t\t<strong>고객센터 문의</strong>\n");
      out.write("\t</h6>\n");
      out.write("\t<hr class=\"deep-purple accent-2 mb-2 mt-0 d-inline-block mx-auto\"\n");
      out.write("\t\tstyle=\"width: 130px;\">\n");
      out.write("\t<p id=\"footercontents\">\n");
      out.write("\t\t<strong>전화문의</strong> 0000-0000<br> <strong>월-금</strong>\n");
      out.write("\t\t9:00-18:00<br> <strong>이메일</strong> aa@aa.com<br>\n");
      out.write("\t</p>\n");
      out.write("</div>\n");
      out.write("<!--/.고객센터 문의n-->\n");
      out.write("\n");
      out.write("<!--입점신청-->\n");
      out.write("<div class=\"col-md-2 col-lg-2 col-xl-3 mx-auto mb-4\">\n");
      out.write("\t<h6 class=\"text-uppercase font-weight-bold\">\n");
      out.write("\t\t<strong>입점신청</strong>\n");
      out.write("\t</h6>\n");
      out.write("\t<hr class=\"deep-purple accent-2 mb-2 mt-0 d-inline-block mx-auto\"\n");
      out.write("\t\tstyle=\"width: 100px;\">\n");
      out.write("\t<p id=\"footercontents\">\n");
      out.write("\t\t<strong>전화문의</strong> 0000-0000<br> <strong>월-금</strong>\n");
      out.write("\t\t9:00-18:00<br> <strong>이메일</strong> aa@aa.com<br>\n");
      out.write("\t</p>\n");
      out.write("</div>\n");
      out.write("<!--/.입점신청-->\n");
      out.write("\n");
      out.write("<!--광고문의-->\n");
      out.write("<div class=\"col-md-3 col-lg-2 col-xl-3 mx-auto mb-4\">\n");
      out.write("\t<h6 class=\"text-uppercase font-weight-bold\">\n");
      out.write("\t\t<strong>광고문의</strong>\n");
      out.write("\t</h6>\n");
      out.write("\t<hr class=\"deep-purple accent-2 mb-2 mt-0 d-inline-block mx-auto\"\n");
      out.write("\t\tstyle=\"width: 100px;\">\n");
      out.write("\t<p id=\"footercontents\">\n");
      out.write("\t\t<strong>전화문의</strong> 0000-0000<br> <strong>월-금</strong>\n");
      out.write("\t\t9:00-18:00<br> <strong>이메일</strong> aa@aa.com<br>\n");
      out.write("\t</p>\n");
      out.write("</div>\n");
      out.write("<!--/.광고문의-->\n");
      out.write("\n");
      out.write("<!--공지사항-->\n");
      out.write("<div class=\"col-md-4 col-lg-3 col-xl-3  mx-auto mb-4\">\n");
      out.write("\t<h6 class=\"text-uppercase font-weight-bold\">\n");
      out.write("\t\t<strong>공지사항</strong>\n");
      out.write("\t</h6>\n");
      out.write("\t<hr class=\"deep-purple accent-2 mb-2 mt-0 d-inline-block mx-auto\"\n");
      out.write("\t\tstyle=\"width: 100px;\">\n");
      out.write("\t<p id=\"footercontents\">\n");
      out.write("\t\t<strong>전화문의</strong> 0000-0000<br> <strong>월-금</strong>\n");
      out.write("\t\t9:00-18:00<br> <strong>이메일</strong> aa@aa.com<br>\n");
      out.write("\t</p>\n");
      out.write("</div>\n");
      out.write("<!--/.공지사항-->\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<!--/.Footer Links-->\n");
      out.write("\n");
      out.write("<!-- Copyright-->\n");
      out.write("<div class=\"footer-copyright py-3 text-center\" id=\"footerbottom\">\n");
      out.write("\t<hr class=\"deep-purple accent-6 mb-4 mt-0 d-inline-block mx-auto\"\n");
      out.write("\t\tstyle=\"width: 1600px;\">\n");
      out.write("\t<br> 이름(주) | 서울특별시 금천구 가산동 371-47 이노플렉스 1차 2층 | 대표: 롸롸 |\n");
      out.write("\t사업자등록번호: 000-00-00000 | 통신판매업 신고번호: 제 2018-서울금천-00000 호<br>\n");
      out.write("\t대표전화: 0000-0000 | Email: aa@aa.com | 개인정보보호책임자: 롸롸, 롸롸<br> ©2018\n");
      out.write("\tMiddle Inc. All Rights Reserved<br>\n");
      out.write("</div>\n");
      out.write("<!--/.Copyright -->\n");
      out.write("</footer>\n");
      out.write("\t\n");
      out.write("<!-- JQuery JavaScript 추가  -->\n");
      out.write("<script type=\"text/javascript\" src=\"../resources/YJH/bootstrap/js/jquery-3.3.1.min.js\"></script>\n");
      out.write("<!-- Popper JavaScript 추가 -->\n");
      out.write("<script type=\"text/javascript\" src=\"../resources/YJH/bootstrap/js/popper.js\"></script>\n");
      out.write("<!-- Bootstrap JavaScript 추가 -->\n");
      out.write("<script type=\"text/javascript\" src=\"../resources/YJH/bootstrap/js/bootstrap.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
